# Laboratorio 6 SDS - Hunting with Data Science
## Ricardo Valenzuela
## Sara Zavala

In [1]:
import json

In [2]:
# Obtencion de datos
f = open("..\data\large_eve.json")
data = []
for i in f.readlines():
    if i:
        data.append(json.loads(i))


print("Cantidad de datos: ", len(data))
f.close()

Cantidad de datos:  746909

In [3]:
# Filtrado de registros DNS
dns_data = []

for j in data:
    if "dns" in j.keys():
        dns_data.append(j)

print("Los registros que tienen datos de dns son: ", len(dns_data))

Los registros que tienen datos de dns son:  15749

In [4]:
#Verificamos que en efecto el registro se de dns_data
print(dns_data[0:2])

[{'timestamp': '2017-07-22T17:33:16.661646-0500', 'flow_id': 1327836194150542, 'pcap_cnt': 22269, 'event_type': 'dns', 'vlan': 110, 'src_ip': '2001:0dbb:0c18:0011:0260:6eff:fe30:0863', 'src_port': 59680, 'dest_ip': '2001:0500:0001:0000:0000:0000:803f:0235', 'dest_port': 53, 'proto': 'UDP', 'dns': {'type': 'query', 'id': 15529, 'rrname': 'api.wunderground.com', 'rrtype': 'A', 'tx_id': 0}}, {'timestamp': '2017-07-22T17:33:24.990320-0500', 'flow_id': 2022925111925872, 'pcap_cnt': 54352, 'event_type': 'dns', 'vlan': 110, 'src_ip': '2001:0dbb:0c18:0011:0260:6eff:fe30:0863', 'src_port': 38051, 'dest_ip': '2001:0500:0003:0000:0000:0000:0000:0042', 'dest_port': 53, 'proto': 'UDP', 'dns': {'type': 'query', 'id': 58278, 'rrname': 'stork79.dropbox.com', 'rrtype': 'A', 'tx_id': 0}}]

In [5]:
# Conversion a dataframe
import pandas as pd
df = pd.json_normalize(dns_data)
df.head()

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,dns.type,dns.id,dns.rrname,dns.rrtype,dns.tx_id,dns.rcode,dns.ttl,dns.rdata
0,2017-07-22T17:33:16.661646-0500,1327836194150542,22269,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680,2001:0500:0001:0000:0000:0000:803f:0235,53,UDP,query,15529,api.wunderground.com,A,0.0,NaN,NaN,NaN
1,2017-07-22T17:33:24.990320-0500,2022925111925872,54352,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051,2001:0500:0003:0000:0000:0000:0000:0042,53,UDP,query,58278,stork79.dropbox.com,A,0.0,NaN,NaN,NaN
2,2017-07-22T17:33:27.379891-0500,578544790391795,54519,dns,150,192.168.205.170,31393,192.168.207.4,53,UDP,query,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,0.0,NaN,NaN,NaN
3,2017-07-22T17:33:27.380146-0500,578544790391795,54520,dns,150,192.168.207.4,53,192.168.205.170,31393,UDP,answer,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,NaN,NaN,NXDOMAIN,NaN,NaN
4,2017-07-22T17:33:27.380146-0500,578544790391795,54520,dns,150,192.168.207.4,53,192.168.205.170,31393,UDP,answer,54724,<root>,SOA,NaN,NXDOMAIN,20864.0,NaN

In [6]:
# Filtrado de registros DNS tipo A
filtered_df = df[df['dns.rrtype'] == 'A']
print("Registros DNS de tipo A:", len(filtered_df))

Registros DNS de tipo A: 2849

In [7]:
unique_df = filtered_df.drop_duplicates(subset=['dns.rrname'])
print("Registros unicos DNS de tipo A:", len(unique_df))
unique_df.head()

Registros unicos DNS de tipo A: 177

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,dns.type,dns.id,dns.rrname,dns.rrtype,dns.tx_id,dns.rcode,dns.ttl,dns.rdata
0,2017-07-22T17:33:16.661646-0500,1327836194150542,22269,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680,2001:0500:0001:0000:0000:0000:803f:0235,53,UDP,query,15529,api.wunderground.com,A,0.0,NaN,NaN,NaN
1,2017-07-22T17:33:24.990320-0500,2022925111925872,54352,dns,110,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051,2001:0500:0003:0000:0000:0000:0000:0042,53,UDP,query,58278,stork79.dropbox.com,A,0.0,NaN,NaN,NaN
2,2017-07-22T17:33:27.379891-0500,578544790391795,54519,dns,150,192.168.205.170,31393,192.168.207.4,53,UDP,query,54724,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,0.0,NaN,NaN,NaN
6,2017-07-22T17:33:38.537426-0500,2167545251640146,55687,dns,180,192.168.198.62,35092,192.168.207.4,53,UDP,query,7425,safebrowsing.clients.google.com.home,A,0.0,NaN,NaN,NaN
9,2017-07-22T17:33:45.672579-0500,541745511744323,56307,dns,120,192.168.202.172,55580,192.168.207.4,53,UDP,query,12854,fxfeeds.mozilla.com,A,0.0,NaN,NaN,NaN

In [8]:
# Obtencion de los TLD del data frame de registros unicos DNS de tipo A
from features import domain_tld_extract
unique_df['tld_flare'] = unique_df['dns.rrname'].apply(domain_tld_extract)

C:\Users\Zephyrus\AppData\Local\Temp\ipykernel_9048\1457577457.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df['tld_flare'] = unique_df['dns.rrname'].apply(domain_tld_extract)

In [9]:
unique_df['tld_flare']

nan_value = float("NaN")
unique_df.replace("", nan_value, inplace=True)

unique_df.dropna(subset = ["tld_flare"], inplace=True)

C:\Users\Zephyrus\AppData\Local\Temp\ipykernel_9048\3627101851.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df.replace("", nan_value, inplace=True)
C:\Users\Zephyrus\AppData\Local\Temp\ipykernel_9048\3627101851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df.dropna(subset = ["tld_flare"], inplace=True)

In [10]:
for i in unique_df['tld_flare']:
    print(i)

wunderground.com
dropbox.com
aoltw.net
safebrowsing.clients.google.com.home
mozilla.com
metasploit.com
aol.com
aoltw.net
aol.com
aol.com
aoltw.net
aol.com
google.com
wpad.home
stayonline.net
aoltw.net
aol.com
aol.com
192.168.22.110phpmyadmin
informaction.com
secure.informaction.com.localdomain
safebrowsing.clients.google.com.localdomain
vmware.com
mozilla.com
192.168.22.110phpmyadmin.localdomain
windows.com
vmware.com
ntkrnlpa.info
portswigger.net
offensive-security.com
stayonline.net
stopbadware.org
aoltw.net
arrancar.org
sql-ledger.org
backtrack-linux.org
stayonline.net
mozilla.com
theanime.cn
theanime.cn
aoltw.net
aoltw.net
aoltw.net
safebrowsing.clients.google.com.hackerlabs.vpn
stayonline.net
aoltw.net
aol.com
aoltw.net
phpmyadmin.net
google.com
google.com
microsoft.com
secure.informaction.com.home
aoltw.net
comcast.net
google.com
aoltw.net
ubuntu.com
mozilla.com
alexa.com
postgresql.org
sourceforge.net
freepbx.org
secure.informaction.com.hackerlabs.vpn
bigflickrfeed.com
gnu.org
wpad
safebrowsing.clients.google.com.lan
google.com
comcast.net
sourceforge.net
"192.168.206.56"
freepbx.org
acunetix.com
acunetix.com
microsoft.com
windowsupdate.com
microsoft.com
flickr.com
alexa.com
microsoft.com
aol.com
malwarecity.com
facebook.com
comcast.net
comcast.net
securityfocus.com
xmarks.com
192.168.26-27.0
cakephp.org
hec.net
google.com
adams.net
uidaho.edu
pdx.edu
clarkson.edu
rackspace.com
ecvps.com
wisc.edu
facebook.net
easynews.com
bluehost.com
netriplex.com
stanford.edu
tummy.com
fastserv.com
kernel.org
hmc.edu
liquidweb.com
5ninesolutions.com
fastserv.com
interworx.info
wallawalla.edu
sanctuaryhost.com
team-cymru.org
umoss.org
gigenet.com
xmission.com
upenn.edu
tds.net
nyi.net
atlantic.net
usf.edu
rocketinternet.net
rit.edu
google.com
FL
apple.com
apple.com
xmarks.com
aol.com
saruman
google.com
stayonline.net
aoltw.net
192.168.21.1201
me.com
apple.com
me.com
apple.com
google.com
youtube.com
me.com
msftncsi.com
kodapp.com
threatspace.net
msftncsi.com
backblaze.com
social-engineer.org
microsoft.com
whitecell.localdomain
arduino.cc
aol.com
mac.com
nvidia.com
mozilla.org
mozilla.org
mac.com
nagios.org
vtlfccmfxlkgifuf.com
aoltw.net
macromates.com
1922.168.22.254
google.com
1922.168.22.254.home
192.168.21-28.0
ejfodfmfxlkgifuf.xyz
192.168.21-28.0.home
192.168.22.201:
aol.com
aoltw.net
ntp.ubuntu.com.localdomain
microsoft.com
verisign.com
192.168.22.201:.stayonline.net
real.com

In [11]:
from urllib.parse import urlparse
import re
def this_domain(name):
    return urlparse(name).hostname

feature_df = pd.DataFrame()
urls = unique_df['tld_flare']
feature_df['f1'] = unique_df['tld_flare'].str.len()
feature_df['f2'] = (unique_df['tld_flare'].apply(lambda x: urlparse(x).hostname).str.len()).fillna(0)
feature_df['f4'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '.'))
feature_df['f5'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '-'))
feature_df['f6'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '@'))
feature_df['f7'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '?'))
feature_df['f8'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '&'))
feature_df['f9'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '|'))
feature_df['f10'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '='))
feature_df['f11'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '_'))
feature_df['f12'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '˜'))
feature_df['f13'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '%'))
feature_df['f14'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '/'))
feature_df['f15'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '*'))
feature_df['f16'] = unique_df['tld_flare'].apply(lambda x: str.count(x, ':'))
feature_df['f17'] = unique_df['tld_flare'].apply(lambda x: str.count(x, ','))
feature_df['f18'] = unique_df['tld_flare'].apply(lambda x: str.count(x, ';'))
feature_df['f19'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '$'))
feature_df['f20'] = unique_df['tld_flare'].apply(lambda x: str.count(x, '%20')) + unique_df['tld_flare'].apply(lambda x: str.count(x, ' '))
feature_df['f25'] = unique_df['tld_flare'].apply(lambda x: 1 if 'https' in x else 0)
feature_df['f26'] = unique_df['tld_flare'].apply(lambda x: len(re.findall('[0-9]', x)) / len(x))
feature_df['f27'] = (unique_df['tld_flare'].apply(this_domain).str.count('[0-9]') / unique_df['tld_flare'].apply(this_domain).str.len()).fillna(0)

In [12]:
feature_df

,f1,f2,f4,f5,f6,f7,f8,f9,f10,f11,...,f14,f15,f16,f17,f18,f19,f20,f25,f26,f27
0,16,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
1,11,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
2,9,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
6,36,0,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
9,11,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15632,26,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
15661,13,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
15701,12,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0
15716,30,0,5,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0.366667,0
15737,8,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,0

In [13]:
from joblib import load
# Uso del modelo utilizado en el lab 1
clf = load('my_model.joblib')

predicions = clf.predict(feature_df)

In [14]:
print("Resultados para los registros DNS tipo A: (1 es verdadero, 0 falso)")
predicions

Resultados para los registros DNS tipo A: (1 es verdadero, 0 falso)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0],
      dtype=int64)

In [15]:
filter_registers = []
for i in predicions:
    if i == 0:
        filter_registers.append(False)
    else:
        filter_registers.append(True)

In [16]:
print("Registros a tomar en cuenta:")
unique_df[filter_registers]['tld_flare']

Registros a tomar en cuenta:

6                  safebrowsing.clients.google.com.home
163                            192.168.22.110phpmyadmin
191         safebrowsing.clients.google.com.localdomain
293                192.168.22.110phpmyadmin.localdomain
796      safebrowsing.clients.google.com.hackerlabs.vpn
845                        secure.informaction.com.home
996              secure.informaction.com.hackerlabs.vpn
1072                safebrowsing.clients.google.com.lan
1195                                   "192.168.206.56"
1836                                    192.168.26-27.0
6898                                    192.168.21.1201
9979                                    1922.168.22.254
10048                              1922.168.22.254.home
10607                                   192.168.21-28.0
14730                              192.168.21-28.0.home
15507                                   192.168.22.201:
15632                        ntp.ubuntu.com.localdomain
15716                    192.168.22.201:.stayonline.net
Name: tld_flare, dtype: object

In [17]:
from features import dga_classifier
dga = dga_classifier()

[*] Initializing... training classifier - Please wait.
[+] Training classifier on training set

C:\Users\Zephyrus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[+] Out of sample legit f1 score 0.9989047635763681
[+] Out of sample dga f1 score 0.6430205949656752
[+] Training final classifier

C:\Users\Zephyrus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[+] Classifier Ready

In [20]:
unique_df['good'] = unique_df['tld_flare'].apply(dga.predict)

C:\Users\Zephyrus\AppData\Local\Temp\ipykernel_9048\3092289745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df['good'] = unique_df['tld_flare'].apply(dga.predict)

In [23]:
unique_df[unique_df['good'] == 'dga']['tld_flare']

9856     vtlfccmfxlkgifuf.com
10048    1922.168.22.254.home
10646    ejfodfmfxlkgifuf.xyz
14730    192.168.21-28.0.home
Name: tld_flare, dtype: object